### ISSUE TITLE
我应该如何正常使用？

### ISSUE THREAD

**Issue by qaz6750** [BigfootACA/simple-init#2]

**Comment by BigfootACA** [comment]
是要arm32架构的吗

**Comment by qaz6750** [comment]
是的，谢谢

**Comment by BigfootACA** [comment]
目前还没适配arm32架构，之后会添加适配

**Comment by qaz6750** [comment]
好的，谢谢

**Comment by qaz6750** [comment]
如果可以，在之后我可以测试arm32，我有个Lumia930

**Comment by BigfootACA** [comment]
arm32现在已经添加了
[e31ce3bd5c594b3f82c48afd6a9eddec2018b3b1](https://github.com/BigfootACA/simple-init/commit/e31ce3bd5c594b3f82c48afd6a9eddec2018b3b1)

**Comment by qaz6750** [comment]
![IMG20220528004136 jpg(1)](https://user-images.githubusercontent.com/66907230/170743628-b08baf45-6f38-4a0f-b3b1-a3d44137a04e.jpg)

**Comment by qaz6750** [comment]
我应该怎么做，谢谢你

**Comment by qaz6750** [comment]
我通过 
 FILE DRIVER = af9763a2-033b-4109-8e17-56a98d380c92 {
    SECTION PE32 = Lumia930Pkg/Binary/KernelFdtDxe/KernelFdtDxe.efi
    SECTION UI = "KernelFdtDxe"
  }
解决了这个问题

**Comment by BigfootACA** [comment]
现在可以正常运行吗

**Comment by qaz6750** [comment]
是的

**Comment by qaz6750** [comment]
我应该怎么修改simpleinit.static.uefi.cfg，对于Lumia，他没有logfs分区

**Comment by BigfootACA** [comment]
你可以把simpleinit.static.uefi.cfg保存到任意uefi下能找到的fat分区，目前版本的simpleinit会自动搜寻并加载

**Comment by BigfootACA** [comment]
现在simpleinit还未支持在arm32平台上的linux-boot（如启动linux内核，启动安卓等）

**Comment by qaz6750** [comment]
> 现在simpleinit还未支持在arm32平台上的linux-boot（如启动linux内核，启动安卓等）

谢谢你，我将期待他可以运行linux-boot

**Comment by qaz6750** [comment]
![88B771364216473A875BA4F6B1AE57A5](https://user-images.githubusercontent.com/66907230/170817795-76b3c0d0-7840-48d5-8719-47fad602b474.jpg)
确实如此
