### ISSUE TITLE
如何支持在启动arm32平台上的linux-boot

### ISSUE THREAD

**Issue by qaz6750** [BigfootACA/simple-init#3]

**Comment by qaz6750** [comment]
好的，现在可以了

**Comment by BigfootACA** [comment]
还未实现，目前只能通过uefi的方式启动

**Comment by qaz6750** [comment]
但很奇怪，我昨晚突然可以启动linux

**Comment by qaz6750** [comment]
现在可以启动linux，但对于twrp并没有启动，他没有提醒一些错误

**Comment by BigfootACA** [comment]
如果真的能使用无uefi的方式启动的话那就是奇迹了，那块代码我只顾写完全没有经过测试

**Comment by qaz6750** [comment]
https://www.bilibili.com/video/BV1mT41157hq?share_medium=android&share_plat=android&share_source=QQ&share_tag=s_i&timestamp=1655632738&unique_k=enS9CBH

如视频，但好像受到一些因素的限制

**Comment by qaz6750** [comment]
![屏幕截图 2022-06-19 180254](https://user-images.githubusercontent.com/66907230/174475780-e33965d9-0bf7-4f81-9b1f-193a75abd902.jpg)

**Comment by BigfootACA** [comment]
视频中确实是使用uefi的方式

**Comment by qaz6750** [comment]
好吧
