### ISSUE TITLE
如何编译？

### ISSUE THREAD

**Issue by qaz6750** [BigfootACA/simple-init#4]
我无法正常的编译
![屏幕截图 2022-06-27 183608](https://user-images.githubusercontent.com/66907230/175922649-94593839-5f24-40c2-8e76-79f7b80b25e0.jpg)
，

**Comment by BigfootACA** [comment]
请问具体的编译器版本是？

**Comment by qaz6750** [comment]
gcc version 5.5.0 (Linaro GCC 5.5-2017.10)

**Comment by BigfootACA** [comment]
这个gcc确实有点老了...可以考虑升级到新的版本
或者是尝试把对应那几行的main变量名换成别的应该就能解决。我是没想到会和c入口main函数冲突，后面新提交会给改掉

**Comment by qaz6750** [comment]
![屏幕截图 2022-07-06 185508](https://user-images.githubusercontent.com/66907230/177534916-5e5d8a22-8230-4dbb-9ac8-1ea0b1718506.jpg)
当我在msm8998加入时，无法编译，好像是edk的问题
