### ISSUE TITLE
手机连接USB HUB后无法从U盘启动

### ISSUE THREAD

**Issue by XZHStudio** [BigfootACA/simple-init#9]
既然已经支持从U盘启动了，那可以支持下USB HUB吗？
目前的情况是这样的：
我在尝试在我的手机上启动Ventoy，然后把U盘接上了手机，Ventoy成功启动了，但是尝试按音量键来选择启动项的时候报错了（见图片，目前还无法确定是Ventoy还是simple init的问题），然后我打算通过USB HUB来额外接一个键盘进行操作，但是连接USB HUB后simple init直接无法启动了，日志见视频，而且奇怪的是当我拔下U盘后又正常启动了

设备型号：
小米8

资源如下
![QQ图片20241123200259](https://github.com/user-attachments/assets/e8a82b88-6da4-4603-97ba-542fef805613)
[视频.zip](https://github.com/user-attachments/files/17879603/default.zip)

Ventoy项目地址：github.com/ventoy/Ventoy

**Comment by BigfootACA** [comment]
simple-init不实现usb等功能，该问题是固件（UEFI）导致的
